include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
  rules:
    avoid_empty_else: true

    # Prevents unnecessary allocation of a field
    avoid_field_initializers_in_const_classes: true

    # Removes redundant `= null;`
    avoid_init_to_null: true

    avoid_unnecessary_containers: true

    avoid_unused_constructor_parameters: true

    # Prevents leaks and code executing after their lifecycle.
    cancel_subscriptions: true

    constant_identifier_names: true

    unnecessary_string_interpolations: true

    unnecessary_null_in_if_null_operators: true

    unnecessary_null_checks: true

    unnecessary_null_aware_assignments: true

    unnecessary_new: true

    unnecessary_brace_in_string_interps: true

    avoid_classes_with_only_static_members: false

    sort_pub_dependencies: false

    avoid_print: false

    prefer_final_locals: false

    close_sinks: true

    empty_statements: true

    #Don't use more than one case with same value.
    no_duplicate_case_values: true

    #Don't put any logic in createState.
    no_logic_in_create_state: true

    #Put required named parameters first.
    always_put_required_named_parameters_first: true

    #Prefer using ??= over testing for null.
    prefer_conditional_assignment: true

    #Use isEmpty for Iterables and Maps.
    prefer_is_empty: true

    #Use isNotEmpty for Iterables and Maps.
    prefer_is_not_empty: true

    #Only use double quotes for strings containing single quotes.
    prefer_single_quotes: true







