name: bronco_trucking
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  http: ^1.1.0
  shimmer: ^3.0.0
  intl: ^0.18.1

  #  connectivity: ^3.0.6
  #  connectivity_for_web: ^0.4.0+1
  connectivity_plus: 5.0.2

  shared_preferences: ^2.0.6
  get: ^4.6.1
  flutter_svg: ^2.0.9
  get_it: ^7.2.0
  lint: ^2.2.0
  faker: ^2.0.0
  image_picker: ^1.0.4
  hand_signature: ^3.0.1
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0

  universal_io: ^2.0.4
  universal_platform: ^1.0.0+1

  path_provider: ^2.0.5
  cached_network_image: ^3.1.0
  image_size_getter: ^2.1.2
  logger: ^2.0.2+1

  equatable: ^2.0.3
  dropdown_below: ^1.0.3

#  flutter_stripe_payment: 0.0.17

#  stripe_sdk: ^4.0.2







# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

  fonts:
#    - family: ProzaLibre
#      fonts:
#        - asset: assets/fonts/ProzaLibre_Regular.ttf
#        - asset: assets/fonts/ProzaLibre_Bold.ttf
#        - asset: assets/fonts/ProzaLibre_SemiBold.ttf
#          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Regular.ttf
        - asset: assets/fonts/OpenSans_SemiBold.ttf
          weight: 600
